theme = "dracula"
client_id = "17a6fae045b241e8866ebb966ec33c23"
app_refresh_duration_in_ms = 20
playback_refresh_duration_in_ms = 0
cover_image_refresh_duration_in_ms = 200
track_table_item_max_len = 32
enable_media_control = false
default_device = "spotify-player"
play_icon = "⏸"
pause_icon = "▶"
cover_img_length = 40
cover_img_width = 15
playback_window_width = 16

[device]
name = "spotify-player"
device_type = "speaker"
volume = 50
bitrate = 160
audio_cache = false
